<?xml version="1.0"?><doc>
<members>
<member name="T:Vector3" decl="false" source="D:\Documents\Courses\ODU\MSIM 641\2020\Fall\Programming Assignments\P2\Transportation - Base\Project\Project\src\Vector3D.h" line="3">
\struct Vector3
Structure for storing a 3D vector.
</member>
<member name="M:printString(std.basic_string&lt;System.SByte!System.Runtime.CompilerServices.IsSignUnspecifiedByte,std.char_traits{System.SByte!System.Runtime.CompilerServices.IsSignUnspecifiedByte},std.allocator&lt;System.SByte!System.Runtime.CompilerServices.IsSignUnspecifiedByte&gt;&gt;)" decl="true" source="D:\Documents\Courses\ODU\MSIM 641\2020\Fall\Programming Assignments\P2\Transportation - Base\Project\Project\src\utility.h" line="12">
Display text at the current raster position using font GLUT_BITMAP_9_BY_15.
\param str String to be displayed.
</member>
<member name="M:printLargeString(std.basic_string&lt;System.SByte!System.Runtime.CompilerServices.IsSignUnspecifiedByte,std.char_traits{System.SByte!System.Runtime.CompilerServices.IsSignUnspecifiedByte},std.allocator&lt;System.SByte!System.Runtime.CompilerServices.IsSignUnspecifiedByte&gt;&gt;)" decl="true" source="D:\Documents\Courses\ODU\MSIM 641\2020\Fall\Programming Assignments\P2\Transportation - Base\Project\Project\src\utility.h" line="16">
Display text at the current raster position using font GLUT_BITMAP_HELVETICA_18.
\param str String to be displayed.
</member>
<member name="M:computeRotatedVector(Vector3,System.Single)" decl="true" source="D:\Documents\Courses\ODU\MSIM 641\2020\Fall\Programming Assignments\P2\Transportation - Base\Project\Project\src\utility.h" line="20">
Compute a Vector3 rotated around y axis based on an input Vector3 and an angle.
\param input Input Vector3
\param angle Angle of rotation
\return Resulting Vector3 generated by rotating input around y axis for the angle.
</member>
</members>
</doc>